ARM: imx: built and use IMX busfreq only if CONFIG_HAVE_IMX_BUSFREQ is enabled
This commit fixes multiple redefinitions which prevents kernel from
compiling when CONFIG_HAVE_IMX_BUSFREQ is not enabled. This is observed
since include/linux/busfreq-imx.h provides empty stubs when
CONFIG_HAVE_IMX_BUSFREQ is not enabled, which redefined ones defined in
busfreq-imx.c.

Before this patch built failed with below:

arch/arm/mach-imx/busfreq-imx.c:183:5: error: redefinition of ‘register_busfreq_notifier’
  183 | int register_busfreq_notifier(struct notifier_block *nb)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from arch/arm/mach-imx/busfreq-imx.c:23:
./include/linux/busfreq-imx.h:64:19: note: previous definition of ‘register_busfreq_notifier’ was here
   64 | static inline int register_busfreq_notifier(struct notifier_block *nb)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~
arch/arm/mach-imx/busfreq-imx.c:189:5: error: redefinition of ‘unregister_busfreq_notifier’
  189 | int unregister_busfreq_notifier(struct notifier_block *nb)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from arch/arm/mach-imx/busfreq-imx.c:23:
./include/linux/busfreq-imx.h:68:19: note: previous definition of ‘unregister_busfreq_notifier’ was here
   68 | static inline int unregister_busfreq_notifier(struct notifier_block *nb)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/arm/mach-imx/busfreq-imx.c:821:6: error: redefinition of ‘request_bus_freq’
  821 | void request_bus_freq(enum bus_freq_mode mode)
      |      ^~~~~~~~~~~~~~~~
In file included from arch/arm/mach-imx/busfreq-imx.c:23:
./include/linux/busfreq-imx.h:58:20: note: previous definition of ‘request_bus_freq’ was here
   58 | static inline void request_bus_freq(enum bus_freq_mode mode)
      |                    ^~~~~~~~~~~~~~~~
arch/arm/mach-imx/busfreq-imx.c:870:6: error: redefinition of ‘release_bus_freq’
  870 | void release_bus_freq(enum bus_freq_mode mode)
      |      ^~~~~~~~~~~~~~~~
In file included from arch/arm/mach-imx/busfreq-imx.c:23:
./include/linux/busfreq-imx.h:61:20: note: previous definition of ‘release_bus_freq’ was here
   61 | static inline void release_bus_freq(enum bus_freq_mode mode)
      |                    ^~~~~~~~~~~~~~~~
arch/arm/mach-imx/busfreq-imx.c:946:5: error: redefinition of ‘get_bus_freq_mode’
  946 | int get_bus_freq_mode(void)
      |     ^~~~~~~~~~~~~~~~~
In file included from arch/arm/mach-imx/busfreq-imx.c:23:
./include/linux/busfreq-imx.h:72:19: note: previous definition of ‘get_bus_freq_mode’ was here
   72 | static inline int get_bus_freq_mode(void)

Signed-off-by: Grzegorz Jaszczyk <grzegorz.jaszczyk@linaro.org>