MLK-24874-5: include: uapi: ipu: fix the UAPI_HEADER_TEST failure
Enable CONFIG_UAPI_HEADER_TEST turns on the following build issue
./usr/include/linux/ipu.h:167:2: error: unknown type name ‘u32’
  u32 x;
  ^~~
./usr/include/linux/ipu.h:168:2: error: unknown type name ‘u32’
  u32 y;
  ^~~
./usr/include/linux/ipu.h:173:2: error: unknown type name ‘u32’
  u32 w;
  ^~~
./usr/include/linux/ipu.h:174:2: error: unknown type name ‘u32’
  u32 h;
  ^~~
./usr/include/linux/ipu.h:179:2: error: unknown type name ‘u8’
  u8 motion; /*see ipu_motion_sel*/

The fix is to use the __u32/__u8 instead and remove the internal definiton

But it finally will result in another failure as the followings:

HDRTEST usr/include/linux/ipu.h
In file included from ./usr/include/linux/ipu.h:29:0,
                 from <command-line>:32:
./usr/include/linux/videodev2.h:2353:20: error: field ‘timestamp’ has incomplete type
  struct timespec   timestamp;

This is kernel known issue. The fix is as others by adding the ipu.h to skip-list:
header-test- += linux/v4l2-mediabus.h
header-test- += linux/v4l2-subdev.h
header-test- += linux/videodev2.h

Signed-off-by: Jason Liu <jason.hui.liu@nxp.com>
(cherry picked from commit 24c36527086fff43595bde2822f8277138ebcb55)