touchscreen: synaptics: Use kernel_siginfo instead of siginfo
Use kernel_siginfo instead of siginfo to fix the build errors.

drivers/input/touchscreen/synaptics_dsx/synaptics_dsx_rmi_dev.c:427:27: error: passing argument 2 of ‘send_sig_info’ from incompatible pointer type [-Werror=incompatible-pointer-types]
    send_sig_info(SIGTERM, &rmidev->terminate_signal, task);
                           ^
In file included from ./include/linux/ptrace.h:7:0,
                 from ./arch/arm/include/asm/kgdb.h:14,
                 from ./include/linux/kgdb.h:20,
                 from ./include/linux/fb.h:5,
                 from drivers/input/touchscreen/synaptics_dsx/synaptics_dsx_core.h:45,
                 from drivers/input/touchscreen/synaptics_dsx/synaptics_dsx_rmi_dev.c:47:
./include/linux/sched/signal.h:329:12: note: expected ‘struct kernel_siginfo *’ but argument is of type ‘struct siginfo *’
 extern int send_sig_info(int, struct kernel_siginfo *, struct task_struct *);
            ^~~~~~~~~~~~~

Signed-off-by: Shawn Guo <shawn.guo@linaro.org>