MLK-24874-3: include: uapi: mxc_v4l2: fix the UAPI_HEADER_TEST failure
Eanble CONFIG_UAPI_HEADER_TEST turns out the following build issues:

  HDRTEST usr/include/linux/mxc_v4l2.h
In file included from <command-line>:32:0:
./usr/include/linux/mxc_v4l2.h:52:2: error: unknown type name ‘uint32_t’
  uint32_t u_offset;
  ^~~~~~~~
./usr/include/linux/mxc_v4l2.h:53:2: error: unknown type name ‘uint32_t’
  uint32_t v_offset;
  ^~~~~~~~
./usr/include/linux/mxc_v4l2.h:57:2: error: unknown type name ‘__u32’
  __u32   type; /* enum v4l2_buf_type */
  ^~~~~

The fix is to add the necessary header file into mxc_v4l2.h

Signed-off-by: Jason Liu <jason.hui.liu@nxp.com>
(cherry picked from commit ca2be4571361d04aa291e0ed0fcb755feba8783a)